# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 16:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depot', '0004_auto_20170313_1448'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('returned', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depot.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('purpose', models.CharField(blank=True, max_length=256)),
                ('start_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('state', models.CharField(choices=[('1', 'pending'), ('2', 'approved'), ('3', 'declined'), ('4', 'revoked')], default='1', max_length=1)),
                ('items', models.ManyToManyField(through='rental.ItemRental', to='depot.Item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='itemrental',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.Rental'),
        ),
    ]
