# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0004_auto_20170313_1448'),
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='depot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='depot.Depot'),
            preserve_default=False,
        ),
    ]
