# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_rental_depot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='rental',
            name='lastname',
            field=models.CharField(default='mustermann', max_length=256),
            preserve_default=False,
        ),
    ]
