# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_auto_20170327_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='purpose',
            field=models.CharField(max_length=256),
        ),
    ]
