# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-08 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_auto_20170408_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='firstname',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='rental',
            name='lastname',
            field=models.CharField(max_length=32),
        ),
    ]
