# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0002_auto_20170310_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
