# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0006_auto_20170317_1551'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('name', 'depot')]),
        ),
    ]
