# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0007_auto_20170327_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
