# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0008_auto_20170330_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='visibility',
            field=models.CharField(choices=[('1', 'public'), ('2', 'private'), ('3', 'deleted')], max_length=1),
        ),
    ]
