# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-06 17:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0009_auto_20170330_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='managers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
