# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-04 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0012_item_wikidata_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='visibility',
            field=models.CharField(choices=[('1', 'public'), ('2', 'internal'), ('3', 'deleted')], max_length=1),
        ),
    ]
