# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-01 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0014_auto_20180531_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='description_de',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='depot',
            name='description_en',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description_de',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='description_en',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name_de',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='name_en',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
