# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-06-24 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depot', '0015_auto_20180601_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='wikidata_item',
        ),
    ]
